language: ruby
rvm:
  - 2.6.3

install: gem install jekyll html-proofer
script: jekyll build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false