language: ruby
rvm:
- 2.6.3
install: bundle install
script: jekyll build
cache: bundler
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAQ4WU3QSDVVLHFEMX
  secret_access_key:
    secure: zF3fod49wrK9JPtW6hcWtlKaEHx1zI81ANIYQOtG8I1XbSwo1No/FDgOYQaM1KxyNT1W7dWdYv6ENCopgqcmYZzYbf5OhSUapix1CHUmqQxSXaCVaug0y8ux5ZEET4XqolBtPaAh8Q0ScODmRNT3J3yTOTgBoP24qwmz6mn8LMRC1nSghOpPvpmj/4YnXPgtlcTMKUAQRMDwNgPVaYwh6MJ0v0YVNU3ZXjDS7Uzs+n0Yi13aWlRuwmwRv2spSHrYfSi5FiQSDq46pYlmR44HliLvirUZogDQ/yMtQql2fWFp6LeIFnOM9SZ27TyNPetDY7UDrxGHHDS0pY7wK5D/BGaYhrbv2x8uHJ6HxWLKD0QJoIHEid0WYbo17qm/Hpals1Mp/a5c8735f0ymXdoSXTFij2xy5sG5lWYJoYPS3NocAWTXj2gYFRZqDMPXntix8LS6nxDbOtTGPl9SLwiakOaqWDDMOvpDb0zYRJY2UrpWqu0U7T54KbfTUDLhO4wDf/ZkbZx+LDtoYiLMKAIF6mMJF8vOmJvIjDzHhT/oiOZ9fHfvGifA8hlIAxPLHLA0Dp9oxMw6yhM5vjneSpd9I+v98QtId8pVSxeunMVhoMqibFI0W6qjuiNiB6PFGWHjf6I9INCIay/Cb+FKY79RZassQxyicvKTq1giHenwxNE=
  bucket: com.folkol.blog
  local-dir: _site
  acl: public_read
  on:
    repo: folkol/blog.folkol.com
  skip_cleanup: 'true'
env:
  global:
    secure: TL3ntIi4JodHZIDiv56hKjf02YBh7y3GbohcUJlZLWW0cvOh8vHQTb7vzvEJeqApfffY0GQcoOk3O6HUZoYZhsebaQsKb4/G4uplRRLZh4MM61g/5N64jSqPlSvX96oFjvsH51mJQI33gpMPNe99XU4yLKyOQueWQY2KOu6HguNdd7pxO04ZGNzFMbez0feDHvyBtRc/Ten/T4fU33KP3kVq/bCfOfzXapWZDeBKSDlrvdbVYO3QMEnpUiUGALOFN06P913diDcgKhdZrXuJ3RnxtcVDGl8e/Iqp9ZcDG3BqEfur5yLhSEneRiksgdl//yi9XhNB6d69AYKQ3iqt5wydT/r3hAyxg9RgeIQlLJAQV+I2CeTxNEiIYrtxf/bmlltITCHLymadDLPip4c3oHbVifrnHfeCqSsphPeNrB36Kc9U9kDzHvkqxA3vFVZAeyAMb8lKESn5Q98zhlCLhCzuHOFOGGyngoAatR6aCpH6tSImiZ8/qFJLDuwmWTd2IWBK+nQmD2s0xuV3Di5YhxWGRdw2DWcAksd7hJmKXYsn5Gi+H8GIiJFPfY8B18KNuJAgOgEnAyf9056/Ar3EefIJXWvfUHJiVJZ4Dt4afaKkAVLdZGuVa3fXqPpdVsg0QW7p3+i/q06omaOyxkq9wFCf0Vpgh0k79TksSlM8XDg=
